services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: leilao-app
        container_name: leilao-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - leilao-network
        depends_on:
            - mysql
            - redis

    worker:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: leilao-worker
        container_name: leilao-worker
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: php artisan horizon
        networks:
            - leilao-network
        depends_on:
            - app
            - redis
            - mysql

    nginx:
        image: nginx:alpine
        container_name: leilao-nginx
        restart: unless-stopped
        ports:
            - "8001:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - leilao-network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: leilao-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - leilao-network
        ports:
            - "3307:3306"

    redis:
        image: redis:alpine
        container_name: leilao-redis
        restart: unless-stopped
        volumes:
            - redisdata:/data
        networks:
            - leilao-network
        ports:
            - "6379:6379"

    soketi:
        image: quay.io/soketi/soketi:latest-16-alpine
        container_name: leilao-soketi
        restart: unless-stopped
        environment:
            SOKETI_DEBUG: "1"
            SOKETI_METRICS_SERVER_PORT: "9601"
        ports:
            - "6001:6001"
            - "9601:9601"
        networks:
            - leilao-network

networks:
    leilao-network:
        driver: bridge

volumes:
    dbdata:
    redisdata:
